[package]
name = "hsb-engine"
version = "0.1.0"
edition = "2021"

[build-dependencies]
tauri-build = "1"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "1", features = ["api-all"] }
